### ISSUE TITLE
你的创业团demo页没了jq 没效果了…… 

### ISSUE THREAD

**Issue by lgh06** [bh-lay/stick#2]
http://bh-lay.com/topic/intiate/index.html

**Comment by lgh06** [comment]
是这样的 有人问我瀑布流 我就想到了这个 结果demo页面挂了…… aha……

**Comment by bh-lay** [comment]
这个页面我已经删掉了，竟然忘了CDN还有缓存。
可以看下我的博客列表页面，也是瀑布流的设计，页面和使用到的代码都在下面。

http://bh-lay.com/blog
https://github.com/bh-lay/stick

**Comment by lgh06** [comment]
好 thx。我自己撸是没啥问题。  
只是简洁的demo没了 新blog好多无关代码 外加压缩了…… 辛苦了新手……

**Comment by lgh06** [comment]
挨个计算div块的位置 绝对定位 感觉有些残暴……

**Comment by bh-lay** [comment]
是残暴，还有点儿惨不忍睹 😭
